### ISSUE TITLE
Thumbnail Missing

### ISSUE THREAD

**Issue by VrTech** [fabimc/strapi-provider-upload-ftp#7]
I've successfully uploaded the files but the images are shown and linked to
`localhost:1337/myimagelink`
instead of my host?

How to fix this?

**Comment by fabimc** [comment]
there's probably a problem with your configuration.
Are you getting any errors?

**Comment by VrTech** [comment]
I'm not sure but I'll close for now. Will further update if found a solution.

**Comment by VrTech** [comment]
@fabimc 
Hi, do you have any examples of these parameters? 

       basePath: env("FTP_BASEPATH"),
       baseUrl: env("FTP_BASEURL"),

As for now I use this
```
FTP_BASEPATH=/mysitefoldername/
FTP_BASEURL=https://mysite.name/
```

I try to configure this might solve the problem
